import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { Analytics } from "@vercel/analytics/next";
import { cn } from "@/lib/utils";
import { AnimatedMenuDemo } from "@/components/ui/Menu";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const chauPhilomene = localFont({
  src: "./fonts/ChauPhilomeneOne-Regular.ttf",
  variable: "--font-chau-philomene",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        geistSans.variable,
        geistMono.variable,
        chauPhilomene.variable,
        "font-sans",
        inter.variable,
      )}
    >
      <body className="min-h-full flex flex-col justify-center  ">
        {/* <AnimatedMenuDemo /> */}
        {children}
      </body>
      <Analytics />
    </html>
  );
}
